### PR TITLE
Release/4.0.1

### PR DESCRIPTION
**Pull request by frankinspace**
### Added
- [issues/95](https://github.com/MAAP-Project/maap-py/issues/95): Added github action workflow for publishing and switched to poetry for builds

### CODE REVIEW

**Comment by frankinspace** [comment]
Draft status until we resolve the permission error with the CICD app

**Comment by frankinspace** [comment]
CICD permissions have been fixed. Example release candidate: 
- https://github.com/MAAP-Project/maap-py/releases/tag/4.0.1rc1
- https://test.pypi.org/project/maap-py/4.0.1rc1/

Can be installed via `pip install -i https://test.pypi.org/simple/ maap-py==4.0.1rc1`

**Comment by grallewellyn** [comment]
Does this resolve: https://github.com/MAAP-Project/Community/issues/801? And why are we merging directly into master instead of develop then develop into master?

**Comment by frankinspace** [comment]
> Does this resolve: [MAAP-Project/Community#801](https://github.com/MAAP-Project/Community/issues/801)? And why are we merging directly into master instead of develop then develop into master?
@grallewellyn 

Yes, this will resolve [MAAP-Project/Community#801](https://github.com/MAAP-Project/Community/issues/801).

This is being released as a patch release in order to bypass changes that have been merged to develop but we don't want to release yet. So this change is branched directly from the 4.0.0 tag to isolate the CICD changes only as 4.0.1. Once this gets merged to `master` it will get merged back into `develop`

**Comment by sujen1412** [comment]
This looks good. 

Will this parse the version number for the next release from the release branch ? 
What would the workflow look like going forward after this get merged into develop ?

**Review by sujen1412 — APPROVED** [review]

**Comment by grallewellyn** [comment]
I tried to add this to maap-workspaces, but there are dependency conflicts I was trying to resolve in the branch feature/maap-py-401

**Comment by frankinspace** [comment]
@sujen1412 
> Will this parse the version number for the next release from the release branch ? 

Yes, on the first commit pushed to a `release/*` branch, the version of the software being built will not contain the string `rc` and `BUMP_RC` will be set to `false`:
https://github.com/MAAP-Project/maap-py/blob/7b75d55eda1bb971438598adab3098c98cb439e8/.github/workflows/build-pipeline.yml#L97-L98

When `BUMP_RC` is `false`, the version is set to the portion of the branch name that follows `release/` and then `rc1` is appended:
https://github.com/MAAP-Project/maap-py/blob/7b75d55eda1bb971438598adab3098c98cb439e8/.github/workflows/build-pipeline.yml#L103

So for example, if a new branch is created called `release/4.0.1`, the version gets set to `4.0.1rc1` (https://github.com/MAAP-Project/maap-py/actions/runs/10292743817/job/28681643438). The next commit to the `release/4.0.1` will have `rc` in the version already so `BUMP_RC` is set to `true` and instead of parsing the branch name, it will just increment the `rc` number by 1.

> What would the workflow look like going forward after this get merged into develop ?

The workflow is the same as maap-api-nasa. Normal development workflow:

1. Create github issue describing the proposed change and why it is needed
2. Create branch from `develop` named `issues/##` where ## is the issue number from step 1. The name of the branch is not required to be issues/*, it can be any of (feature/**, issue/**, issues/**). But in my experience, I just find it easier to copy the last segment of the URL when the issue page is open and use that as the branch name. Also, again just based on my experience, there is no need to differentiate in the branch name whether it is a feature, bugfix, hotfix, etc... all of that can be done using labels on the issue itself. This encourages us to have better record keeping habits and ensure that every change to the codebase is documented. There are some situations (documentation typos, quick lint fixes, one-line changes etc...) that may not need an issue opened but they should hopefully be few and far between. In those cases, a short descriptive name should follow the `issue/` prefix and the commit message would need to be sufficient documentation for the change. If you can't explain the change in a short commit message, an issue should be opened instead.
3. Once development for the change is complete on the `issues/*` branch, open a PR back to `develop`. Make sure the title of the PR includes the issue number and short description of the change. This is the first opportunity for review from other team members. You can tag the `MAAP-Project/platform` team as reviewers to notify folks that it is ready for review. Fill out the new PR template as much as possible and note where/why the guidelines in the PR template were or were not followed.
4. Upon approval of the PR, the change is squash-merged into `develop`. Squash-merge is important here because it allows the development on the `issues/*` branch to have as many commits as necessary. Commit and push to `issues/*` branches as often as possible. The squash-merge at this phase will cause all commits to be squashed into a single commit on the `develop` branch. The commit message for this squashed commit should be the issue number followed by either the title or the description of the PR.
5. Other issues or features are developed following the same process and squash-merged back to `develop`
6. By some agreement (deadline, discussion, demo date, etc...) a release is agreed to containing all of the changes in develop and a release manager is identified. It is at this point the team/release manager needs to make a judgement call of what type (major, minor, patch) of release this is based on the changes that are being included in this release. Once agreed, the release manager will create a `release/#.#.#` branch from `develop` where #.#.# is the agreed version number. This will start building release candidates of the software.
7. Once the `release/` branch is cut, open a PR from `release/` to `master`. This PR should be titled 'Release #.#.#' and the description should contain the contents of the CHANGELOG for this release as well as any "release notes" that users need to be aware of when upgrading their software. Then, begin to test the release candidate software. Ensure documentation is in place for the release. Run `poetry update` to update dependency versions. If there is any change needed for this release before it gets approved, changes can be submitted via a PR (and squash-merged) targeting the `release/` branch. Changes to `release/` branches should be limited only to fixing what was agreed to be delivered in this release, there is no adding on more features to a release once a release branch is cut. Release branches should be short-lived (under a week) unless there is a very good (or serious problem) reason for delaying the release. Every push to a `release/` branch will generate a new `rc` for that release to facilitate testing. All testing results can be recorded in the PR.
8. Once approved, the `release/` branch should be merged to `master` using a merge-commit in order to preserve the commit history from `develop`. This will trigger a build which will strip the `rc` number from the version and then create a final release and upload to pypi.
9. After the `master` build completes, the release manager will merge `master` back into `develop`. There will be merge conflicts on the project version in the pyproject.toml file that will need to be resolved by the Release Manager.


If there is an urgent need for a release but there are already changes present on develop, then the Bugfix/Hotfix workflow can be followed:

1. Instead of branching from `develop`, checkout the tag that needs to be patched and create a `release/#.#.#` branch from that tag. In this situation the release should be a patch release so the release number will simply increment the patch version.
2. The changes needed should be committed to the `release/` branch. Depending on the nature of the fix an `issues/` branch could be created from `release/` to facilitate development and documentation of the fix.
3. Continue with steps 7, 8, 9 of the normal workflow to finish the release.

**Comment by frankinspace** [comment]
> I tried to add this to maap-workspaces, but there are dependency conflicts I was trying to resolve in the branch feature/maap-py-401

@grallewellyn are the dependency conflicts caused by this release candidate?

**Comment by grallewellyn** [comment]
Output of dependency conflicts: https://repo.dit.maap-project.org/root/maap-workspaces/-/jobs/14510 
maap-py v4.0.0 is currently in the maap workspace builds and it is not causing dependency conflicts

**Comment by sujen1412** [comment]
>  I just find it easier to copy the last segment of the URL when the issue page is open and use that as the branch name

I agree with this branch naming scheme as its easier to capture more context in the issue itself. I have been using `community-#` as names as our issues are sometimes created in another repo. But we can talk about consolidating that later.

**Comment by sujen1412** [comment]
> Output of dependency conflicts: https://repo.dit.maap-project.org/root/maap-workspaces/-/jobs/14510 maap-py v4.0.0 is currently in the maap workspace builds and it is not causing dependency conflicts

@grallewellyn These issues are occuring because pip is only looking at test.pypi. 
To test this correctly we need 
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.python.org/simple maap-py==4.0.1rc1
```

**Comment by frankinspace** [comment]
> Edit: @frankinspace This issue could have been caught in a simple maap-py install in a clean python env. Something to think about for adding a simple test to CI/CD (not in this ticket)
@sujen1412 
Good point, I have done that for other repos where after publish there is an additional 'verify' step that just runs a `pip install` of the library that was just uploaded.

**Comment by frankinspace** [comment]
> I have been using `community-#` as names as our issues are sometimes created in another repo. 

I think that's fine. I'd recommend `issues/reponame/##` in this case

**Comment by grallewellyn** [comment]
Ah okay, thank you @sujen1412 
Successful build: https://repo.dit.maap-project.org/root/maap-workspaces/-/jobs/14513
Can successfully use maap-py in this image: 'mas.dit.maap-project.org/root/maap-workspaces/jupyterlab/python:0a1e4ca'

**Comment by grallewellyn** [comment]
If I add back in the package versions that are currently in develop for the python base image and keep the install command as `pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.python.org/simple maap-py==4.0.1rc1`, I get these dependency conflicts:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
#12 11.63 aiobotocore 2.13.2 requires botocore<1.34.132,>=1.34.70, but you have botocore 1.34.159 which is incompatible.
#12 11.63 Successfully installed boto3-1.34.159 botocore-1.34.159 chroma-py-0.1.0.dev1 colour-0.1.5 configparser-7.0.0 geojson-3.1.0 importlib-resources-6.4.0 maap-py-4.0.1rc1 mapboxgl-0.10.2 pyyaml-6.0.2 requests-2.32.3
```
https://repo.dit.maap-project.org/root/maap-workspaces/-/jobs/14516
I resolved similar issues before by changing the boto3 version in maap-py to 1.34.41, but it is 1.34.139 with this PR

**Comment by grallewellyn** [comment]
@frankinspace Changing the maap-py install in the environment.yml to `git+https://github.com/MAAP-Project/maap-py.git@4.0.1rc1` and removing `boto3` from the base_images/environment.yml has no errors in the build: https://repo.dit.maap-project.org/root/maap-workspaces/-/jobs/14541 and I can still run `import boto3` in a Jupyter notebook

**Pull request merged**
