### PR TITLE
Make Result.getData raise exception on failed HTTP download

### LINKED ISSUE #24: Granule file download silently succeeds on "access denied" error
When invoking the `Granule.getData` method, if an "access denied" error occurs, the method "succeeds" and simply writes the following XML (but not pretty-printed) to the destination file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>BXZJR0SFXQKY5YAS</RequestId>
    <HostId>...T2WhGWg=</HostId>
</Error>
```

Expected behavior: the method should _not_ write anything to the destination file and it should throw an exception.

### PR DESCRIPTION
**Pull request by chuckwondo**
Fixed `Result.getData` such that when it uses HTTP to attempt to download a granule file, and the download fails (even after attempting to handle a 401 response), it raises an exception for the status. Previously, such errors appeared to succeed, but rather than having downloaded the data file, the body of the error was written to the output file instead.

Such erroneous behavior leads to problems in client code that assumes the granule file was downloaded, when in fact it was not, and then ends up raising an error attempting to read the granule file under the assumption that it is a data file of the expected format, when it is actually a text file containing an error message.

Fixes #24

### CODE REVIEW

**Review by bsatoriu — APPROVED** [review]
Thank you, @chuckwondo ! These changes look great.

**Comment by chuckwondo** [comment]
@bsatoriu, my pleasure. Thanks for reviewing and approving.

Before I merge this, I have a few questions:

1. Should the version number in `setup.py` be bumped from `0.3.0` to `0.3.1`?
2. Related to versioning, should we be tagging to allow specifying a version to use with `pip`? For example, I'm currently including this in my `requirements.txt` file in another project: `git+https://github.com/MAAP-Project/maap-py.git#egg=maappy`, but that will always cause a clone of the HEAD from `master`, rather than a specific tag.
3. I just noticed a `develop` branch. Should I be merging to that branch instead of to `master`?

**Comment by bsatoriu** [comment]
@chuckwondo 
1. Yes, please increment to `0.3.1`
2. Yes, I'd say go ahead and tag this version. We're pulling from master for all of our MAAP builds currently, and we'll need to start using tags now that we're tagging workspace images.
3. Yes, please merge into `develop`. I'd like to move this PR into master once the F2F is complete this month.

**Comment by chuckwondo** [comment]
I rebased onto `develop`, and adjusted my test case accordingly. I also noticed that your changes to the download logic introduced a bug, so I corrected that as well.

Since I'm now going to merge this into `develop` instead of `master`, I suggest that I bump the version to `0.4.0` instead of `0.3.1` since it appears that the `develop` branch has added some DPS handling as part of the download logic, or is that also considered a "patch" (thus deserving only a patch number, not a new minor version number)?

Once you let me know the version number, I'll bump it (to either 0.3.1 or 0.4.0) and then merge to `develop`.

**Comment by bsatoriu** [comment]
@chuckwondo thanks for the bug fix. Let's go with `0.4.0` for this set of changes, given the scope. Thanks!

**Pull request merged**
