### PR TITLE
Improve dependency constraints

### LINKED ISSUE #76: Loosen dependency version constraints to permit flexible dependency resolution
For this project, dependencies are specified in `setup.py`, but there are 3 issues with how they are specified:

1. Most of them include _no_ version constraint. In general, all dependencies should at least be constrained to a major version to avoid unintended breakages from introduction of new major version releases
2. Only 2 include a version constraint, and they are [version matching](https://peps.python.org/pep-0440/#version-matching) clauses (`==`, i.e., _exact_ version match), which is rarely necessary, and can often be detrimental to dependency resolution. Instead, [compatible release](https://peps.python.org/pep-0440/#compatible-release) clauses (`~=`, flexible, but constrained to a particular _major_ version only) are generally preferred.
3. Several dev/test dependencies are listed in the _required_ dependencies, which is undesirable. They should be moved from `install_requires` to `test_requires`.

We should clean up these dependencies as outlined above, to allow for more flexible dependency resolution, while constraining to major versions to avoid potential breakages when new major dependency versions with breaking changes are released.

### PR DESCRIPTION
**Pull request by chuckwondo**
Improve dependency constraints:
    
- Pinned major versions of all dependencies w/compatible releases
- Moved dev/test deps out of required deps to extra deps
- Changed name from `maapPy` to `maap-py` to match package name
  and allow `maap-py` to be used with conda-lock
    
Fixes #76, #75

### CODE REVIEW

**Comment by grallewellyn** [comment]
Testing the images now, why wasn't the version of setuptools pinned?

**Comment by chuckwondo** [comment]
> Testing the images now, why wasn't the version of setuptools pinned?

Good question. We could do, and probably should. Unfortunately, `setuptools` doesn't use semver conventions, so it's not obvious when breaking changes are introduced by simply looking at the major version number, thus requiring reading the changelog continually.

I suspect we can pin it as `~=69.0`, so let me know how your image testing goes. If all is well, check the version of `setuptools` that got installed in the image. I imagine it will be the latest version (69.0.3), and if so, I'll update the PR with it pinned as `~=69.0`, or whatever makes sense for what was installed.

**Comment by grallewellyn** [comment]
isce3 vanilla and pangeo images are all passing with no dependency errors 
r is failing right now, even in the develop branch so I will look into that tomorrow to confirm the versions for maap-py are good

**Comment by grallewellyn** [comment]
Just to update, for r I am getting this error `aiobotocore 2.11.1 requires botocore<1.34.28,>=1.33.2, but you have botocore 1.34.30 which is incompatible.` when building, so I am working on resolving it

**Review by grallewellyn — CHANGES_REQUESTED** [review]
Can we change _requirements to have 
"boto3~=1.33,<1.34.0",?

That fixes the dependency issue

**Comment by chuckwondo** [comment]
Ah, great! I'll change it to `boto3~=1.33.0`, which will allow only the patch version to vary (i.e., it's does the same thing as `~=1.33,<1.34.0`)

**Comment by chuckwondo** [comment]
Oh. What version of `setuptools` was installed on the image?

**Comment by grallewellyn** [comment]
69.0.3 for the all images

**Comment by grallewellyn** [comment]
I am not seeing the <1.34.0 constraint for boto3

**Comment by chuckwondo** [comment]
> Ah, great! I'll change it to `boto3~=1.33.0`, which will allow only the patch version to vary (i.e., it's does the same thing as `~=1.33,<1.34.0`)

As mentioned above, I changed it to `boto3~=1.33.0`, which implies `<1.34`

**Comment by grallewellyn** [comment]
Ah okay I missed the extra .0, thank you! 
This runs successfully without dependency errors

**Review by grallewellyn — APPROVED** [review]
No dependency errors for all images

**Pull request merged**
